import { StyleSheet } from "react-native";
import { SafeAreaInsetsType, ThemeType } from "../../types/global";

export const getStyles = (theme: ThemeType, insets: SafeAreaInsetsType) =>
  StyleSheet.create({
    homeContainer: {
      flex: 1,
      backgroundColor: theme.bg,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 16,
      paddingHorizontal: 20,
    },
    headerTitleContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    headerLogo: {
      width: 48,
      height: 48,
      padding: 0,
    },
    headerTitle: {
      fontFamily: "TitilliumWeb-Black",
      color: theme.accent,
      fontSize: 32,
      padding: 0,
      margin: 0,
      marginBottom: 4,
    },
    emptyState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 40,
    },
    emptyText: {
      color: "#fff",
      fontSize: 20,
      fontWeight: "600",
      marginTop: 16,
    },
    emptySubText: {
      color: theme.textLight,
      fontSize: 16,
      textAlign: "center",
      marginTop: 8,
    },
    gridList: {
      padding: 10,
    },
    floatingIslandContainer: {
      position: "absolute",
      bottom: 30,
      left: 20,
      right: 20,
      alignItems: "center",
      justifyContent: "center",
      zIndex: 1000,
    },
    floatingIslandBlur: {
      borderRadius: 30,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 95%, 85%, 0.24)`,
      borderBottomColor: `hsla(${theme.hue}, 90%, 80%, 0.14)`,
      backgroundColor: `hsla(${theme.hue}, 54%, 9%, 0.75)`,
      elevation: 8,
      shadowColor: "#000",
      shadowOpacity: 0.35,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
    },
    floatingIslandInner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 22,
      paddingVertical: 14,
      width: "100%",
    },
    islandLeft: {
      flexDirection: "row",
      alignItems: "center",
    },
    islandDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.accent,
      marginHorizontal: 8,
    },
    islandCount: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "500",
    },
    islandRight: {
      flexDirection: "row",
      alignItems: "center",
    },
    islandButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.buttonBg,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 80%, 0.12)`,
      borderTopColor: `hsla(${theme.hue}, 100%, 85%, 0.25)`,
    },
    islandImportButton: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.buttonBg,
      justifyContent: "center",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 80%, 0.12)`,
      borderTopColor: `hsla(${theme.hue}, 100%, 85%, 0.25)`,
    },
    islandImportButtonText: {
      color: theme.buttonText,
      fontSize: 13,
      fontWeight: "bold",
      marginLeft: 6,
    },
  });
