import { Dimensions, StyleSheet } from "react-native";
import { SafeAreaInsetsType, ThemeType } from "../../types/global";

const { width } = Dimensions.get("window");

export const getStyles = (theme: ThemeType, insets: SafeAreaInsetsType) =>
  StyleSheet.create({
    tutorialOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.85)",
      zIndex: 1000,
      justifyContent: "center",
    },
    highlightRsvp: {
      position: "absolute",
      top: "38%",
      height: "24%",
      left: "5%",
      right: "5%",
      borderWidth: 2,
      borderColor: theme.accent,
      borderStyle: "dashed",
      borderRadius: 12,
      backgroundColor: "rgba(255, 255, 255, 0.03)",
    },
    highlightWpm: {
      position: "absolute",
      bottom: (insets.bottom || 0) + 170,
      height: 44,
      width: 140,
      borderWidth: 2,
      borderColor: theme.accent,
      borderStyle: "dashed",
      borderRadius: 20,
      backgroundColor: "rgba(255, 255, 255, 0.03)",
    },
    highlightTopBar: {
      position: "absolute",
      top: (insets.top || 0) + 20,
      left: 10,
      right: 10,
      height: 60,
      borderWidth: 2,
      borderColor: theme.accent,
      borderStyle: "dashed",
      borderRadius: 20,
      backgroundColor: "rgba(255, 255, 255, 0.03)",
    },
    highlightControls: {
      position: "absolute",
      bottom: (insets.bottom || 0) + 30,
      alignSelf: "center",
      width: 330,
      height: 80,
      borderWidth: 2,
      borderColor: theme.accent,
      borderStyle: "dashed",
      borderRadius: 30,
      backgroundColor: "rgba(255, 255, 255, 0.03)",
    },
    tutorialHand: {
      position: "absolute",
      top: "50%",
      alignSelf: "center",
      marginTop: -18,
      zIndex: 20,
    },
    tutorialCardContainer: {
      position: "absolute",
      left: 20,
      right: 20,
      elevation: 10,
      shadowColor: "#000",
      shadowOpacity: 0.5,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 5 },
    },
    tutorialCardBlur: {
      borderRadius: 24,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 95%, 85%, 0.24)`,
      borderBottomColor: `hsla(${theme.hue}, 90%, 80%, 0.14)`,
      backgroundColor: `hsla(${theme.hue}, 54%, 9%, 0.75)`,
    },
    tutorialCardInner: {
      padding: 24,
      alignItems: "center",
      position: "relative",
    },
    tutorialSkipButton: {
      position: "absolute",
      top: 16,
      right: 20,
      padding: 6,
      zIndex: 10,
    },
    tutorialSkipText: {
      color: theme.textMuted,
      fontSize: 14,
      fontWeight: "600",
    },
    tutorialHeaderIcon: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: `hsla(${theme.hue}, 100%, 60%, 0.08)`,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 85%, 0.12)`,
    },
    tutorialTitle: {
      color: "#fff",
      fontSize: 20,
      fontWeight: "bold",
      marginBottom: 8,
      textAlign: "center",
    },
    tutorialText: {
      color: theme.textLight,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 22,
      marginBottom: 16,
    },
    tutorialDotsContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    tutorialDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginHorizontal: 4,
    },
    tutorialDotActive: {
      backgroundColor: theme.accent,
      width: 18,
    },
    tutorialDotInactive: {
      backgroundColor: `hsla(${theme.hue}, 15%, 50%, 0.3)`,
    },
    checkboxContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 16,
      paddingHorizontal: 10,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 15%, 50%, 0.4)`,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
      backgroundColor: "rgba(255, 255, 255, 0.02)",
    },
    checkboxChecked: {
      backgroundColor: theme.accent,
      borderColor: theme.accent,
    },
    checkboxLabel: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "500",
    },
    tutorialButton: {
      width: "100%",
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.buttonBg,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 80%, 0.12)`,
      borderTopColor: `hsla(${theme.hue}, 100%, 85%, 0.25)`,
    },
    tutorialButtonText: {
      color: theme.buttonText,
      fontSize: 14,
      fontWeight: "bold",
    },
  });
