import { StyleSheet } from "react-native";
import { SafeAreaInsetsType, ThemeType } from "../../types/global";

export const getStyles = (theme: ThemeType, insets: SafeAreaInsetsType) =>
  StyleSheet.create({
    readerContainer: {
      flex: 1,
      backgroundColor: theme.bg,
    },
    topBar: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 8,
    },
    leftSideArea: {
      width: 88,
      alignItems: "flex-start",
    },
    titleContainer: {
      flex: 1,
      alignItems: "center",
      paddingHorizontal: 10,
      marginTop: 4,
    },
    backButton: {
      padding: 4,
    },
    bookTitle: {
      color: theme.textLight,
      fontSize: 16,
      textAlign: "center",
    },
    chapterTitle: {
      color: theme.textMuted,
      fontSize: 18,
      fontWeight: "bold",
      textAlign: "center",
      marginTop: 28,
    },
    fontControls: {
      width: "auto",
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
    },
    miniIslandBlur: {
      borderRadius: 20,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 95%, 85%, 0.24)`,
      borderBottomColor: `hsla(${theme.hue}, 90%, 80%, 0.14)`,
      backgroundColor: `hsla(${theme.hue}, 54%, 9%, 0.75)`,
      elevation: 4,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
    },
    miniIslandInner: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    miniIslandButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.buttonBg,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 80%, 0.12)`,
      borderTopColor: `hsla(${theme.hue}, 100%, 85%, 0.25)`,
    },
    miniIslandButtonText: {
      color: theme.buttonText,
      fontSize: 13,
      fontWeight: "bold",
    },
    rsvpContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      overflow: "visible",
    },
    guideLineTop: {
      position: "absolute",
      top: "50%",
      marginTop: -10,
      width: 2,
      height: 20,
      backgroundColor: theme.textDark,
    },
    guideLineBottom: {
      position: "absolute",
      top: "50%",
      marginTop: -10,
      width: 2,
      height: 20,
      backgroundColor: theme.textDark,
    },
    scrubIndicatorContainer: {
      position: "absolute",
      top: "20%",
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      zIndex: 10,
    },
    scrubArrow: {
      marginHorizontal: -25,
    },
    wordWrapper: {
      flexDirection: "row",
      alignItems: "center",
      width: "100%",
      overflow: "visible",
    },
    leftPartContainer: {
      flex: 1,
      alignItems: "flex-end",
      overflow: "visible",
    },
    centerPartContainer: {
      alignItems: "center",
      overflow: "visible",
    },
    rightPartContainer: {
      flex: 1,
      alignItems: "flex-start",
      overflow: "visible",
    },
    wordText: {
      color: "#fff",
      fontWeight: "bold",
      fontFamily: "monospace",
    },
    redLetter: {
      color: theme.accent,
    },
    progressText: {
      position: "absolute",
      bottom: 40,
      color: theme.textMuted,
      fontSize: 14,
    },
    controlsContainer: {
      paddingBottom: 40,
      alignItems: "center",
    },
    wpmIslandContainer: {
      position: "relative",
      overflow: "visible",
      marginBottom: 20,
    },
    wpmIslandBlur: {
      borderRadius: 20,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 95%, 85%, 0.24)`,
      borderBottomColor: `hsla(${theme.hue}, 90%, 80%, 0.14)`,
      backgroundColor: `hsla(${theme.hue}, 54%, 9%, 0.75)`,
      elevation: 4,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
    },
    wpmIslandInner: {
      paddingHorizontal: 20,
      paddingVertical: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    wpmText: {
      color: "#fff",
      fontSize: 18,
      fontWeight: "bold",
    },
    readerIslandContainer: {
      alignItems: "center",
      justifyContent: "center",
      marginTop: 10,
    },
    readerIslandBlur: {
      borderRadius: 30,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 95%, 85%, 0.24)`,
      borderBottomColor: `hsla(${theme.hue}, 90%, 80%, 0.14)`,
      backgroundColor: `hsla(${theme.hue}, 54%, 9%, 0.75)`,
      elevation: 8,
      shadowColor: "#000",
      shadowOpacity: 0.35,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
    },
    readerIslandInner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 12,
      width: 320,
    },
    readerIslandButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.buttonBg,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 80%, 0.12)`,
      borderTopColor: `hsla(${theme.hue}, 100%, 85%, 0.25)`,
    },
    readerPlayButton: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.buttonBg,
    },
    buttonWrapper: {
      position: "relative",
      justifyContent: "center",
      alignItems: "center",
    },
    buttonGlow: {
      position: "absolute",
      opacity: 0.55,
    },
    contextContainer: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
      zIndex: 10,
      backgroundColor: theme.bg,
    },
    contextText: {
      color: theme.textLight,
      textAlign: "center",
      lineHeight: 32,
    },
  });
