import { StyleSheet } from "react-native";
import { ThemeType } from "../../types/global";

export const getStyles = (theme: ThemeType) =>
  StyleSheet.create({
    bookCardContainer: {
      flex: 1,
      maxWidth: "50%",
      margin: 10,
      height: 220,
      position: "relative",
      zIndex: 1,
    },
    bookCard: {
      width: "100%",
      height: "100%",
      backgroundColor: "rgba(255, 255, 255, 0.03)",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 95%, 85%, 0.22)`,
      borderBottomColor: `hsla(${theme.hue}, 90%, 80%, 0.12)`,
      elevation: 8,
      shadowColor: "#000",
      shadowOpacity: 0.45,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 5 },
    },
    bookCardInner: {
      flex: 1,
      borderRadius: 12,
      overflow: "hidden",
    },
    coverImageContainer: {
      flex: 1,
      width: "100%",
    },
    coverImage: {
      flex: 1,
      width: "100%",
    },
    coverTitleOverlay: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "rgba(0,0,0,0.6)",
      paddingVertical: 8,
      paddingHorizontal: 6,
    },
    coverTitleOverlayText: {
      color: "#fff",
      fontSize: 12,
      textAlign: "center",
    },
    coverPlaceholder: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 16,
      backgroundColor: "rgba(255, 255, 255, 0.01)",
    },
    bookCardTitle: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "500",
      textAlign: "center",
      marginTop: 12,
    },
    uploadCoverHint: {
      color: theme.textMuted,
      fontSize: 12,
      textAlign: "center",
      marginTop: 8,
    },
    progressBadge: {
      position: "absolute",
      bottom: 8,
      right: 8,
      backgroundColor: theme.accent,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
    },
    progressBadgeText: {
      color: theme.textOnAccent,
      fontSize: 12,
      fontWeight: "bold",
    },
    bookCardMenuContainer: {
      position: "absolute",
      bottom: -62,
      left: 0,
      right: 0,
      elevation: 8,
      shadowColor: "#000",
      shadowOpacity: 0.4,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      zIndex: 100,
    },
    bookCardMenuBlur: {
      borderRadius: 20,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 95%, 85%, 0.24)`,
      borderBottomColor: `hsla(${theme.hue}, 90%, 80%, 0.14)`,
      backgroundColor: `hsla(${theme.hue}, 54%, 9%, 0.75)`,
    },
    bookCardMenuInner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 20,
      paddingVertical: 8,
      width: "100%",
    },
    menuOptionButtonTransparent: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: "transparent",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 80%, 0.12)`,
      borderTopColor: `hsla(${theme.hue}, 100%, 85%, 0.25)`,
    },
    menuOptionButtonGlass: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.buttonBg,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: `hsla(${theme.hue}, 100%, 80%, 0.12)`,
      borderTopColor: `hsla(${theme.hue}, 100%, 85%, 0.25)`,
    },
  });
